### ISSUE TITLE
logging関数をUtilsに作る

### ISSUE THREAD

**Issue by tamaroning** [kmc-jp/n64-emu#13]
ログしたいすべての箇所で直接spdlogを使うのは避けたい。
ログ関数をUtilsに作って、そこの中でspdlogを呼び出すようにする。

```cpp
Utils::n64_log_debug(args, ...) {
  spdlog::debug(args...);
}

Utils::n64_log_trace(args, ...) {
  spdlog::trace(args...);
}
```

こうすることで、以下のメリットが有る
- ライブラリの変更や自作ログ関数への切り替えが簡単になる
- 細かいログのカスタマイズが容易になる
- `#include <spdlog>` の必要がなくなる

**Comment by tamaroning** [comment]
C++の可変長引数の関数がよくわからないので調べる。

**Comment by sashi0034** [comment]
実際にゲームを動かすときに、1命令ずつログに書き出すとだいぶ処理落ちするだろうから命令用にログの関数は分けたいかも 
(ゲーム実行用のマクロを定義して、それがあるときは命令用のログを書き出さない的な実装にしたい)

**Comment by tamaroning** [comment]
ログ関数にinline属性を付けて、
関数内をマクロで記述すればログ関数を使ったまま、ログ無効の時はオーバーヘッドなしで実行できるんじゃない？

**Comment by tamaroning** [comment]
そもそも、命令のログは取らなくてもいいね。
今はエミュレータ開発の初期段階だからログ撮ってるけど

**Comment by sashi0034** [comment]
> ログ関数にinline属性を付けて、 関数内をマクロで記述すればログ関数を使ったまま、ログ無効の時はオーバーヘッドなしで実行できるんじゃない？

命令実行以外の場所でもn64_log_debugを使ってるとき、命令実行のログは取りたくないけどそれ以外の場所はログは取りたいってなるかもしれないから、命令用にログの関数は分けるか、ログにタグをつけるかしたいかもって思ってた
(命令ログ取らないなら、関係ないや)

**Comment by tamaroning** [comment]
なるほど、それもアリ。

**Comment by hatsusato** [comment]
> C++の可変長引数の関数がよくわからないので調べる。

std::formatを参考にするとどうでしょう。
https://cpprefjp.github.io/reference/format/format.html
