### ISSUE TITLE
COP0のレジスタ幅について

### ISSUE THREAD

**Issue by sashi0034** [kmc-jp/n64-emu#9]
https://github.com/kmc-jp/n64-emu/blob/acbc3c5d03eed4976b935e1ba6a246340c23826d/src/cpu/cop0.h#L105

64bitレジスタ32個じゃなくて、32bitレジスタが32個かも

**Comment by tamaroning** [comment]
https://n64.readthedocs.io/
レジスタによって幅が違うから、余裕を持たせて64bitにしてたんだけど、レジスタごとに変数を宣言したほうがいい？
こんな感じに
```cpp
index_t index;
uint32_t random;
uint64_t entry_lo;
error_pc_t error_pc;
```

**Comment by sashi0034** [comment]
https://n64.readthedocs.io/#:~:text=for%20what%20purposes.-,COP0%20Registers,-%C2%B6
本当だ、幅違うんだ

**Comment by sashi0034** [comment]
`uint64_t reg[32]; ` のままで、アクセスをread32とread64の関数で分けようと思います (writeも)

**Comment by tamaroning** [comment]
OK.それなら、regはprivateフィールドにして、read32, read64呼び出し時に、assertでレジスタの番号が適切な幅のレジスタかを確認したほうが良さそうです。

**Comment by tamaroning** [comment]
たとえばindexレジスタは32bitなので、それをread64したら、assertでプログラムが落ちるようにしたい。

**Comment by tamaroning** [comment]
これの1.3
https://ultra64.ca/files/documentation/silicon-graphics/SGI_R4300_RISC_Processor_Specification_REV2.2.pdf

> The on-chip system control coprocessor (CP0) uses 25 registers. These registers are 32 bits wide
except for EntryHi, XContext, EPC, and ErrorPC, which are 64 bits wide.
